---

root: true

plugins:
  - jest
  - react

env:
  node: true
  jest: true
  browser: true

parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true

extends:
  - airbnb
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:react/recommended
  - plugin:react-hooks/recommended

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 
    - error
    - allow:
      - __filename
      - __dirname
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
  react/prop-types: 0
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
