services:
  api:
    build:
      context: ./api
    environment:
      DATABASE_HOST: db-test
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - ./api:/app
    networks:
      - network-db
    depends_on:
      - db-test

  db-test:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: postgres
    tmpfs: /var/lib/postgresql/data
    networks:
      - network-db

networks:
  network-db:
