---

root: true

plugins:
  - jest

env:
  node: true
  jest: true

parserOptions:
  ecmaVersion: 2020

extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:jest/style

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 
    - error
    - allow:
      - __filename
      - __dirname
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
  no-unused-expressions:
    - error
    - allowShortCircuit: true
