name: release

on:
  create:
    tags:
      - v*

env:
  API_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cottonraj-warehouse-api
  WEB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cottonraj-warehouse-web

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: docker pull ${{ env.API_IMAGE }}:latest
      - run: docker tag ${{ env.API_IMAGE }}:latest ${{ env.API_IMAGE }}:${{ github.ref_name }}
      - run: docker push ${{ env.API_IMAGE }}:${{ github.ref_name}}

      - run: docker pull ${{ env.WEB_IMAGE }}:latest
      - run: docker tag ${{ env.WEB_IMAGE }}:latest ${{ env.WEB_IMAGE }}:${{ github.ref_name }}
      - run: docker push ${{ env.WEB_IMAGE }}:${{ github.ref_name }}
